
title = "Config file ICAIPose"

[project]
name = "PoseEstimationTrain"
description = "Efficient human pose estimation using modified OpenPose network"
version = "1.0.0"
author = "Simon Walser"

[network]
width_1 = [96, 256] #[96, 256]
width_2 = [96, 256] #[128,512]
width_3 = [96, 256] #[96, 256]
width_4 = [96, 256] #[128,512]
paf_channels  = 28
conf_channels = 16

[training]
img_res = 256
epochs  = 800
lr_boundaries  = [     1,     200,     400,     600]      # In epochs -> it is converted to steps afterwards
lr_values      = [1e-5,  1e-4,    5e-5,    1e-5,    5e-6] # One more than lr_boundaries
evaluate_every = 541                                      # In steps
epoch_list     = [200, 400, 600]
sigma_list     = [13.0, 10.0, 7.0, 5.0]
loss_factors   = [85.0, 85.0, 30.2, 30.2, 29.7]

[data]
src_path = '/mnt/data/s1walser/PhysioAI/Data/poseestimationtrain/256'
dst_path = '/mnt/data/s1walser/PhysioAI/trained_models/poseestimationtrain/256'
# src_path = '/home/simon/work/work_OST/PhysioAI/Data/poseestimationtrain/256'
# dst_path = '/home/simon/work/work_OST/PhysioAI/trained_models/poseestimationtrain/256'
save_attribute = '5'
batch_size = 32
ds_size_train = 51958
ds_size_valid = 2142